version: '3.8'

services:
  db:
    image: mysql:8.0.27
    container_name: school-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schooldb
      MYSQL_PASSWORD: root  
    ports:
      - "3307:3306"

  app:
    image: rahulkishorparida/school-app
    container_name: school-system-app
    ports:
      - "8080:8080"
    depends_on:
      - db
