version: "3.8"

services:
  db:
    image: mysql:8.0.27
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: schooldb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  app:
    image: rahulkishorparida/school-app
    container_name: school-app
    depends_on:
      - db
    ports:
      - "8080:8080"